import Link from 'next/link';
import { ArrowRight, CheckCircle2, MapPin, MessageCircle, Phone } from 'lucide-react';
import { SiteFooter } from '../components/site-footer';
import { SiteHeader } from '../components/site-header';
import { services } from '../components/services-data';

const values = ['Experienced multi-trade team', 'Residential and commercial projects', 'Quality materials and precise finishing'];
const heroServices = services.filter((service) => service.slug !== 'welding');

export default function HomePage() {
  return <main className="min-h-screen bg-white text-ink"><SiteHeader />
    <section className="relative isolate overflow-hidden bg-[#0A1C4F]"><div className="relative mx-auto flex min-h-[68vh] items-center px-4 py-20 sm:px-6 lg:px-8"><div className="max-w-4xl text-white"><p className="text-sm font-bold uppercase tracking-widest text-sky-400">Cape Town property specialists</p><h1 className="mt-5 text-4xl font-extrabold leading-tight text-white sm:text-6xl">Transforming Homes, Estates & Commercial Spaces</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-200">Sky House Finishing delivers painting, solar, electrical, tiling, welding and waterproofing services with thoughtful preparation and dependable workmanship.</p><div className="mt-7 flex flex-wrap gap-3">{heroServices.map(({ slug, navLabel, icon: Icon }) => <span key={slug} className="flex items-center gap-2 rounded-full border border-white/10 bg-white/5 py-1.5 pl-1.5 pr-4 text-xs font-semibold text-white transition-all hover:bg-white/10"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-white/10"><Icon className="h-4 w-4 text-skyBright" /></span>{navLabel}</span>)}</div><div className="mt-8 flex flex-row flex-wrap gap-3"><a href="https://wa.me/27628567694?text=Hi%20Sky%20House%20Finishing!%20I%20would%20like%20to%20get%20more%20information%20about%20your%20services." target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center gap-2 rounded-lg bg-white px-6 py-3.5 font-semibold text-[#0A1C4F] transition-colors hover:bg-slate-100">Request a quote <ArrowRight className="h-4 w-4" /></a><Link href="/projects" className="inline-flex items-center justify-center rounded-lg border border-white/70 px-6 py-3.5 font-semibold text-white transition-colors hover:border-white hover:bg-white/10">View our work</Link></div></div></div></section>
    <section id="about" className="mx-auto grid max-w-7xl gap-10 px-4 py-20 sm:px-6 lg:grid-cols-2 lg:px-8"><div><p className="text-sm font-bold uppercase tracking-[0.2em] text-sky">About us</p><h2 className="mt-4 text-3xl font-bold text-navy sm:text-4xl">Precision craftsmanship, dependable delivery.</h2><p className="mt-5 text-lg leading-8">Based in Milnerton, Sky House Finishing brings skilled trades together for homes, estates and commercial spaces across Cape Town's Western Seaboard. We combine clean workmanship, premium materials and clear communication from preparation to handover.</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{['Precision craftsmanship', 'Clean, respectful sites', 'On-time project delivery', 'Plascon and Dulux materials', 'Full client support', 'Western Seaboard coverage'].map((value) => <p key={value} className="flex items-center gap-3 font-semibold text-navy"><CheckCircle2 className="h-5 w-5 shrink-0 text-sky" />{value}</p>)}</div></div><div className="overflow-hidden rounded-xl border border-gray-200 shadow-lg"><iframe title="Sky House Finishing location in Milnerton" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d26514.872658882855!2d18.4727!3d-33.8647!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1dcc5a3d0d6ef3b%3A0x4d6a8f1f5f1d0e9a!2sMilnerton%2C%20Cape%20Town!5e0!3m2!1sen!2sza!4v1&q=Milnerton,+Cape+Town" className="h-80 w-full border-0 sm:h-full sm:min-h-[360px]" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div></section>
    <section id="contact" className="bg-canvas py-20"><div className="mx-auto grid max-w-7xl gap-10 px-4 sm:px-6 lg:grid-cols-[1fr_.9fr] lg:px-8"><div><p className="text-sm font-bold uppercase tracking-[0.2em] text-sky">Contact</p><h2 className="mt-4 text-3xl font-bold text-navy sm:text-4xl">Tell us about your project.</h2><p className="mt-5 max-w-xl text-lg leading-8">Get in touch for a quotation, site visit or practical advice on your next finishing project.</p></div><div className="grid gap-4 text-sm"><a href="tel:+27628567694" className="flex items-center gap-3 rounded-lg bg-white p-5 shadow-soft transition hover:text-sky"><Phone className="h-5 w-5 text-sky" />+27 62 856 7694</a><a href="https://wa.me/27628567694?text=Hi%20Sky%20House%20Finishing!%20I%20would%20like%20to%20get%20more%20information%20about%20your%20services." target="_blank" rel="noopener noreferrer" className="flex items-center gap-3 rounded-lg bg-white p-5 shadow-soft transition hover:text-sky"><MessageCircle className="h-5 w-5 text-sky" />WhatsApp</a><p className="flex items-center gap-3 rounded-lg bg-white p-5 shadow-soft"><MapPin className="h-5 w-5 text-sky" />Milnerton, Cape Town</p></div></div></section><SiteFooter />
  </main>;
}